// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: proto/tinykvpp/v1/tinykvpp_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TinyKVPPService_Put_FullMethodName = "/tinykvpp.v1.TinyKVPPService/Put"
	TinyKVPPService_Get_FullMethodName = "/tinykvpp.v1.TinyKVPPService/Get"
)

// TinyKVPPServiceClient is the client API for TinyKVPPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TinyKVPPServiceClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type tinyKVPPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTinyKVPPServiceClient(cc grpc.ClientConnInterface) TinyKVPPServiceClient {
	return &tinyKVPPServiceClient{cc}
}

func (c *tinyKVPPServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, TinyKVPPService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyKVPPServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, TinyKVPPService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TinyKVPPServiceServer is the server API for TinyKVPPService service.
// All implementations must embed UnimplementedTinyKVPPServiceServer
// for forward compatibility.
type TinyKVPPServiceServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedTinyKVPPServiceServer()
}

// UnimplementedTinyKVPPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTinyKVPPServiceServer struct{}

func (UnimplementedTinyKVPPServiceServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedTinyKVPPServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTinyKVPPServiceServer) mustEmbedUnimplementedTinyKVPPServiceServer() {}
func (UnimplementedTinyKVPPServiceServer) testEmbeddedByValue()                         {}

// UnsafeTinyKVPPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TinyKVPPServiceServer will
// result in compilation errors.
type UnsafeTinyKVPPServiceServer interface {
	mustEmbedUnimplementedTinyKVPPServiceServer()
}

func RegisterTinyKVPPServiceServer(s grpc.ServiceRegistrar, srv TinyKVPPServiceServer) {
	// If the following call pancis, it indicates UnimplementedTinyKVPPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TinyKVPPService_ServiceDesc, srv)
}

func _TinyKVPPService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyKVPPServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyKVPPService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyKVPPServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyKVPPService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyKVPPServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyKVPPService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyKVPPServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TinyKVPPService_ServiceDesc is the grpc.ServiceDesc for TinyKVPPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TinyKVPPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tinykvpp.v1.TinyKVPPService",
	HandlerType: (*TinyKVPPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _TinyKVPPService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TinyKVPPService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tinykvpp/v1/tinykvpp_service.proto",
}
