// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: proto/tinykvpp/v1/tinykvpp_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseOperation_Type int32

const (
	DatabaseOperation_TYPE_UNSPECIFIED DatabaseOperation_Type = 0
	DatabaseOperation_TYPE_PUT         DatabaseOperation_Type = 1
	DatabaseOperation_TYPE_DELETE      DatabaseOperation_Type = 2
	DatabaseOperation_TYPE_BATCH       DatabaseOperation_Type = 3
)

// Enum value maps for DatabaseOperation_Type.
var (
	DatabaseOperation_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PUT",
		2: "TYPE_DELETE",
		3: "TYPE_BATCH",
	}
	DatabaseOperation_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PUT":         1,
		"TYPE_DELETE":      2,
		"TYPE_BATCH":       3,
	}
)

func (x DatabaseOperation_Type) Enum() *DatabaseOperation_Type {
	p := new(DatabaseOperation_Type)
	*p = x
	return p
}

func (x DatabaseOperation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseOperation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tinykvpp_v1_tinykvpp_service_proto_enumTypes[0].Descriptor()
}

func (DatabaseOperation_Type) Type() protoreflect.EnumType {
	return &file_proto_tinykvpp_v1_tinykvpp_service_proto_enumTypes[0]
}

func (x DatabaseOperation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatabaseOperation_Type.Descriptor instead.
func (DatabaseOperation_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescGZIP(), []int{4, 0}
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// For internal database use
type DatabaseOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  DatabaseOperation_Type `protobuf:"varint,1,opt,name=type,proto3,enum=tinykvpp.v1.DatabaseOperation_Type" json:"type,omitempty"`
	Key   string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Reserve 4 for Batch operations
	RequestId     uint64 `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseOperation) Reset() {
	*x = DatabaseOperation{}
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseOperation) ProtoMessage() {}

func (x *DatabaseOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseOperation.ProtoReflect.Descriptor instead.
func (*DatabaseOperation) Descriptor() ([]byte, []int) {
	return file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescGZIP(), []int{4}
}

func (x *DatabaseOperation) GetType() DatabaseOperation_Type {
	if x != nil {
		return x.Type
	}
	return DatabaseOperation_TYPE_UNSPECIFIED
}

func (x *DatabaseOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DatabaseOperation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DatabaseOperation) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

var File_proto_tinykvpp_v1_tinykvpp_service_proto protoreflect.FileDescriptor

const file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDesc = "" +
	"\n" +
	"(proto/tinykvpp/v1/tinykvpp_service.proto\x12\vtinykvpp.v1\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"=\n" +
	"\vPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xe0\x01\n" +
	"\x11DatabaseOperation\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.tinykvpp.v1.DatabaseOperation.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x04R\trequestId\"K\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTYPE_PUT\x10\x01\x12\x0f\n" +
	"\vTYPE_DELETE\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_BATCH\x10\x032\x85\x01\n" +
	"\x0fTinyKVPPService\x128\n" +
	"\x03Put\x12\x17.tinykvpp.v1.PutRequest\x1a\x18.tinykvpp.v1.PutResponse\x128\n" +
	"\x03Get\x12\x17.tinykvpp.v1.GetRequest\x1a\x18.tinykvpp.v1.GetResponseB/Z-github.com/lnikon/tinykvpp/protos/tinykvpp/v1b\x06proto3"

var (
	file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescOnce sync.Once
	file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescData []byte
)

func file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescGZIP() []byte {
	file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescOnce.Do(func() {
		file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDesc), len(file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDesc)))
	})
	return file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDescData
}

var file_proto_tinykvpp_v1_tinykvpp_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tinykvpp_v1_tinykvpp_service_proto_goTypes = []any{
	(DatabaseOperation_Type)(0), // 0: tinykvpp.v1.DatabaseOperation.Type
	(*PutRequest)(nil),          // 1: tinykvpp.v1.PutRequest
	(*PutResponse)(nil),         // 2: tinykvpp.v1.PutResponse
	(*GetRequest)(nil),          // 3: tinykvpp.v1.GetRequest
	(*GetResponse)(nil),         // 4: tinykvpp.v1.GetResponse
	(*DatabaseOperation)(nil),   // 5: tinykvpp.v1.DatabaseOperation
}
var file_proto_tinykvpp_v1_tinykvpp_service_proto_depIdxs = []int32{
	0, // 0: tinykvpp.v1.DatabaseOperation.type:type_name -> tinykvpp.v1.DatabaseOperation.Type
	1, // 1: tinykvpp.v1.TinyKVPPService.Put:input_type -> tinykvpp.v1.PutRequest
	3, // 2: tinykvpp.v1.TinyKVPPService.Get:input_type -> tinykvpp.v1.GetRequest
	2, // 3: tinykvpp.v1.TinyKVPPService.Put:output_type -> tinykvpp.v1.PutResponse
	4, // 4: tinykvpp.v1.TinyKVPPService.Get:output_type -> tinykvpp.v1.GetResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tinykvpp_v1_tinykvpp_service_proto_init() }
func file_proto_tinykvpp_v1_tinykvpp_service_proto_init() {
	if File_proto_tinykvpp_v1_tinykvpp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDesc), len(file_proto_tinykvpp_v1_tinykvpp_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tinykvpp_v1_tinykvpp_service_proto_goTypes,
		DependencyIndexes: file_proto_tinykvpp_v1_tinykvpp_service_proto_depIdxs,
		EnumInfos:         file_proto_tinykvpp_v1_tinykvpp_service_proto_enumTypes,
		MessageInfos:      file_proto_tinykvpp_v1_tinykvpp_service_proto_msgTypes,
	}.Build()
	File_proto_tinykvpp_v1_tinykvpp_service_proto = out.File
	file_proto_tinykvpp_v1_tinykvpp_service_proto_goTypes = nil
	file_proto_tinykvpp_v1_tinykvpp_service_proto_depIdxs = nil
}
