name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tinykvpp - RelBuild - Clang
        run: cmake --build --preset conan-release --target BuildClangReleaseDockerImage

  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tinykvpp - RelBuild - GCC
        run: cmake --build --preset conan-release --target BuildGCCReleaseDockerImage
