name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tinykvpp - RelBuild - Clang
        run: sh ./scripts/build_clang_release_docker_image.sh

  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tinykvpp - RelBuild - GCC
        run: sh ./scripts/build_gcc_release_docker_image.sh
